[package]
name = "monteparser"
version = "0.1.0"
edition = "2024"

[dependencies]
pyo3 = ">=0.25.0"
chumsky = { version = ">=0.11", Numbers = true}
cstree = ">=0.13"
rowan = ">=0.15"

[lib]
name = "_lib"

path = "monteparser/lib.rs"
crate-type = ["cdylib"]
